# 2.14 Help

## 2.14.1 Helpの活用

In [1]:
import numpy as np
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

# 2.15 関数

## 2.15.1 関数の利用

In [7]:
def my_func1():
    print('Hi!')
    
#関数の定義はここまで
my_func1()

Hi!


In [8]:
my_func1()

Hi!


In [9]:
def my_func2(a,b):
    c=a+b
    
    return c

In [10]:
my_func2(1,2)

3

## 2.15.2 引数と戻り値

In [11]:
def my_func3(D):
    m=np.mean(D)
    s=np.std(D)
    return m,s

In [15]:
data=np.random.randn(100)
data_mean, data_std=my_func3(data)
print('mean:{0:.2f}, std:{1:.2f}'.format(data_mean, data_std))

mean:0.14, std:1.04


In [17]:
output=my_func3(data)
print(output)
print(type(output))
print('mean:{0:.2f}, std:{1:.2f}'.format(output[0], output[1]))

(0.1356904494727041, 1.037535586026517)
<class 'tuple'>
mean:0.14, std:1.04


# 2.16ファイル保存

## 2.16.1 1つのndarray型の保存

In [4]:
import numpy as np
data = np.array([1,1,2,3,5,8,13])
print(data)

np.save('datafile.npy',data) #ファイルの保存
data=[] #データの消去
print(data)

data=np.load('datafile.npy') #ファイル読み出し
print(data)

[ 1  1  2  3  5  8 13]
[]
[ 1  1  2  3  5  8 13]


## 2.16.2 複数のndarray型の保存

In [13]:
data1=np.array([1,2,3])
data2=np.array([10,20,30])
np.savez('datafile2.npz',data1=data1,data2=data2) #ファイル保存
data1=[] #データの消去
data2=[]
outfile=np.load('datafile2.npz') #ファイルの読み出し
print(outfile.files)
data1=outfile['data1']
data2=outfile['data2']
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
