In [1]:
1 / 3

0.3333333333333333

In [2]:
1 + 2 + 3

6

In [3]:
a = 1
b = 7
a / b

0.14285714285714285

機械学習をしよう

# 機械学習をしよう

### 機械学習をしよう

In [4]:
type(100)

int

In [5]:
type(100.1)

float

In [6]:
x=100
type(x)

int

In [7]:
x=100.1
type(x)

float

In [8]:
x = "learneing"
type(x)

str

## print文

In [9]:
x = 1 / 3
x
y = 2 / 3
y

0.6666666666666666

In [11]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


## 文字列と組み合わせた数値の表示1

In [12]:
print('x='+str(x))

x=0.3333333333333333


## 文字列と組み合わせた数値の表示2

In [13]:
print('weight = {}kg'.format(x))

weight = 0.3333333333333333kg


In [14]:
x=1/3
y=1/7
z=1/4
print('weight: {0}kg, {1}kg, {2}kg'.format(x,y,z))

weight: 0.3333333333333333kg, 0.14285714285714285kg, 0.25kg


In [17]:
x=1/3
y=1/7
z=1/4
print('weight: {0:.2f}kg, {1:.2f}kg, {2:.2f}kg'.format(x,y,z))

weight: 0.33kg, 0.14kg, 0.25kg


## 2.5 list

In [1]:
x=[1,1,2,3,5] #listの定義
print(x) #表示

[1, 1, 2, 3, 5]


In [2]:
x[0]

1

In [3]:
x[2]

2

In [4]:
type(x)

list

In [9]:
print(type(x))
print(type(x[0]))

<class 'list'>
<class 'int'>


In [10]:
s=['SUN',1,'MON',2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [11]:
x=[1,1,2,3,5]
x[3]=100
print(x)

[1, 1, 2, 100, 5]


In [12]:
a=[[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [13]:
print(a[0][1])

2


In [18]:
y=range(26,30)
print(y[0],y[1],y[2],y[3])

26 27 28 29


In [19]:
y[2]=2

TypeError: 'range' object does not support item assignment

In [22]:
z=list(y)
print(z)

[26, 27, 28, 29]


In [24]:
print(list(range(100)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


## tuple

In [26]:
a=(1,2,3,4)
print(a)

(1, 2, 3, 4)


In [27]:
a[1]

2

In [28]:
type(a)

tuple

In [29]:
a=(1)
type(a)

int

In [30]:
a=(1,)
type(a)

tuple

## if文

In [35]:
x=11
if x>10:
    print('x is')
    print('     larger than 10.')
else:
    print('x is less smaller than 11')

x is
     larger than 10.


In [36]:
x>10

True

In [37]:
type(x>10)

bool

In [38]:
x=15
if 10<x and x<20:
    print('x is between 10 and 20.')

x is between 10 and 20.


## for文

In [39]:
for i in [1,2,3]:
    print(i)

1
2
3


In [41]:
num=[2,4,6,8,10]
for i in range(len(num)):
    num[i]*=2
print(num)

[4, 8, 12, 16, 20]


In [42]:
num=[2,4,6,8,10]
for i,n in enumerate(num):
    num[i]=n*2
print(num)

[4, 8, 12, 16, 20]


## 2.9ベクトル

In [4]:
list=[1,2]+[3,4]
print(list)
print(type(list))

[1, 2, 3, 4]
<class 'list'>


In [5]:
import numpy as np

In [7]:
x=np.array([1,2])
x

array([1, 2])

In [8]:
print(x)

[1 2]


In [9]:
x=np.array([1,2])
y=np.array([3,4])
print(x+y)

[4 6]


In [10]:
type(x)

numpy.ndarray

In [11]:
x=np.array([1,2])
print(x[0])

1


In [12]:
x=np.array([1,2])
x[0]=100
print(x)

[100   2]


In [15]:
print(np.arange(20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
type(np.arange(20))

numpy.ndarray

### ndarrayの注意点

In [20]:
a=np.array([1,1])
b=a
print('a='+str(a))
print('b='+str(b))
b[0]=100
print('a='+str(a)) #aも変化してしまう
print('b='+str(b))

a=[1 1]
b=[1 1]
a=[100   1]
b=[100   1]


In [22]:
a=np.array([1,1])
b=a.copy()
print('a='+str(a))
print('b='+str(b))
b[0]=100
print('a='+str(a)) #aは変化しない
print('b='+str(b))

a=[1 1]
b=[1 1]
a=[1 1]
b=[100   1]


## 行列

In [26]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [28]:
x.shape

(2, 3)

In [29]:
h,w=x.shape
print(h)
print(w)

2
3


In [30]:
x[1,2]

6

In [31]:
x[1,2]=100
print(x)

[[  1   2   3]
 [  4   5 100]]


In [34]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
x=np.zeros((2,10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
x=np.zeros((2,3,4))
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [43]:
x=np.ones((2,10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [44]:
np.random.rand(4,5)

array([[0.73953296, 0.47678369, 0.41414013, 0.26696511, 0.17864827],
       [0.90755288, 0.39290868, 0.15628908, 0.7478579 , 0.55088357],
       [0.3444522 , 0.15265557, 0.60102601, 0.05024122, 0.35088069],
       [0.43224412, 0.21293039, 0.47053697, 0.58099099, 0.58928923]])

In [45]:
np.random.rand(4,5)

array([[0.49012155, 0.3529496 , 0.78150937, 0.65220901, 0.15749206],
       [0.3408483 , 0.66587327, 0.58737802, 0.69480348, 0.31900435],
       [0.69620192, 0.16343541, 0.8103736 , 0.4850251 , 0.24661918],
       [0.51419991, 0.68224631, 0.8432818 , 0.6562251 , 0.27042056]])

In [46]:
np.random.rand(4,5)

array([[0.77326896, 0.82298428, 0.94838126, 0.81639037, 0.10306359],
       [0.29837508, 0.81809408, 0.95190646, 0.93789616, 0.91944329],
       [0.01355437, 0.28064814, 0.39146281, 0.44349123, 0.97751806],
       [0.31593299, 0.86222785, 0.04857187, 0.9224163 , 0.75879237]])

In [47]:
np.random.randn(4,5)

array([[-0.53159826, -0.58432433, -0.53365926, -1.69256349,  1.85305489],
       [ 0.62943107, -0.25999353, -1.60649477,  0.68190932, -0.34400755],
       [ 0.12613365, -1.36250002,  0.20418487, -0.61669767, -0.62554844],
       [-1.84421029,  2.01886323,  1.36404796,  0.11717193,  0.99422737]])

In [50]:
np.random.randint(0,9,(4,5))

array([[7, 3, 8, 8, 2],
       [4, 1, 7, 2, 0],
       [8, 7, 5, 1, 6],
       [2, 1, 1, 8, 7]])

In [52]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
a=a.reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [56]:
a=a.reshape(5,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [57]:
a=a.reshape(1,10)
print(a)

[[0 1 2 3 4 5 6 7 8 9]]


## 行列(ndarray)の四則演算

In [59]:
x=np.array([[4,4,4],[8,8,8]])
y=np.array([[1,1,1],[2,2,2]])
print(x+y)

[[ 5  5  5]
 [10 10 10]]


In [60]:
print(10*x)

[[40 40 40]
 [80 80 80]]


In [62]:
x=np.array([[4,4,4],[9,9,9]])
print(np.sqrt(x))

[[2. 2. 2.]
 [3. 3. 3.]]


## 2.12 スライシング

In [63]:
x=np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [64]:
print(x[5:])

[5 6 7 8 9]


In [65]:
print(x[3:8])

[3 4 5 6 7]


In [66]:
print(x[3:8:2])

[3 5 7]


In [67]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [70]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y[:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [71]:
x=np.array([1,1,2,3,5,8,13])
x>3

array([False, False, False, False,  True,  True,  True])

In [72]:
x<3

array([ True,  True,  True, False, False, False, False])

In [73]:
x==3

array([False, False, False,  True, False, False, False])

In [74]:
print(x>3)

[False False False False  True  True  True]


In [75]:
x[x>3]

array([ 5,  8, 13])

In [76]:
print(x)

[ 1  1  2  3  5  8 13]


In [77]:
x[x>3]=999
print(x)

[  1   1   2   3 999 999 999]


## Help

In [78]:
import numpy as np
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi