# 4.1 ベクトル

## 4.1.2 Pythonでベクトルを定義する

In [1]:
import numpy as np

In [3]:
a = np.array([2, 1])
print(a)

[2 1]


In [4]:
type(a)

numpy.ndarray

## 4.1.3 縦ベクトルを表す

In [10]:
c = np.array([[1, 2], [3, 4]])
print(c)

[[1 2]
 [3 4]]


In [11]:
d = np.array([[1], [2]])
print(d)
print(type(d))

[[1]
 [2]]
<class 'numpy.ndarray'>


## 4.1.4 転置を表す

In [13]:
print(d.T)
print(d.T.T)

[[1 2]]
[[1]
 [2]]


In [14]:
print(a.T) #転置は1次元ndarrayには有効でない

[2 1]


## 4.1.5 足し算と引き算

In [16]:
a = np.array([2, 1])
b = np.array([1, 3])
print(a + b)
print(a - b)

[3 4]
[ 1 -2]


## 4.1.6 スカラーとの掛け算

In [17]:
print(2 * a)

[4 2]


In [19]:
b = np.array([1, 3])
c = np.array([4, 2])
print(b.dot(c))

10


## 4.1.8 ベクトルの大きさ

In [26]:
a = np.array([1, 3])
print(np.linalg.norm(a))
print(np.around(np.linalg.norm(a), 4))

3.1622776601683795
3.1623


# 4.2 和の記号

## 4.2.2 和を内積として計算する

In [27]:
import numpy as np

a = np.ones(1000)
b = np.arange(1, 1001)
print(a.dot(b))

500500.0


# 4.3積の記号